# Choice of a OS compatible with the targeted version of DESeq2
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

# Update and install required dependencies
RUN apt-get update
RUN apt-get install -y  \
    curl \
    make \
    zlib1g-dev  \
    zlib1g  \
    gfortran  \
    g++  \
    gcc  \
    aptitude  \
    fort77  \
    libbz2-dev  \
    liblzma-dev  \
    libpcre3  \
    libpcre3-dev  \
    libcurl4  \
    libcurl4-openssl-dev  \
    default-jdk  \
    texlive-latex-base  \
    libxml2-dev  \
    libpng-dev  \
    graphviz  \
    libgraphviz-dev  \
    libssl-dev \
    r-base-dev \
    libcairo-dev
RUN aptitude install -y libreadline-dev

# Download and install R 3.4.1
RUN curl -o R_3-4-1.tar.gz https://cran.rstudio.com/src/base/R-3/R-3.4.1.tar.gz && tar -xzf R_3-4-1.tar.gz && rm R_3-4-1.tar.gz
RUN cd R-3.4.1/ && ./configure && make && make install

# Cleanup
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install R dependencies and other packages
RUN R -e "install.packages(c('tidyverse','ggrepel', 'pheatmap', 'Cairo') , repos = 'https://packagemanager.posit.co/cran/__linux__/focal/2018-01-11')"
RUN R -e "install.packages('readxl', repos = 'https://packagemanager.posit.co/cran/__linux__/focal/2018-01-11')"
RUN R -e "install.packages('jsonlite', repos = 'https://packagemanager.posit.co/cran/__linux__/focal/2018-01-11')"
RUN R -e "install.packages('Rgraphviz/', repos = NULL, type='source')" && rm -rf Rgraphviz

# Install BiocInstaller and use it to install the remaining dependencies and packages, plus DESeq2 1.16.1
RUN R -e "install.packages('BiocInstaller', repos = 'https://bioconductor.org/packages/3.5/bioc/')"
RUN R -e "BiocInstaller::biocLite('graph')"
RUN R -e "options(repos = c(CRAN = 'https://packagemanager.posit.co/cran/__linux__/focal/2018-01-11')) ; BiocInstaller::biocLite('DESeq2')"

# Check DESeq2 is installed
RUN R -e 'library("DESeq2")'
